---
# tasks file for pikvm
- name: Remount read-write to prepare for changes
  ansible.builtin.command: rw
  tags:
    - install
    - override
    - security
    - package
    - never
  register: read_write
  changed_when: false
  when: not ansible_check_mode

- name: Ensure the SD card is remounted read-only
  block:
    - name: Include install tasks when indicated by the tags
      ansible.builtin.include_tasks:
        file: install.yml
      tags:
        - install
        - never

    - name: Include override tasks when indicated by the tags
      ansible.builtin.include_tasks:
        file: override.yml
      tags:
        - install
        - override
        - security
        - never

    - name: Include package tasks when indicated by the tags
      ansible.builtin.include_tasks:
        file: package.yml
      tags:
        - install
        - package
        - never

    - name: Include security tasks when indicated by the tags
      ansible.builtin.include_tasks:
        file: security.yml
      tags:
        - install
        - security
        - never

  rescue:
    - name: Bring failed hosts back into play to remount SD card
      ansible.builtin.meta: clear_host_errors

- name: Ensure the SD card is remounted read-only to protect the SD card
  block:
    - name: Remount the SD card read-only
      ansible.builtin.command: ro
      tags:
        - install
        - override
        - security
        - package
        - never
      register: remount_task
      changed_when: remount_task.rc != 0
      failed_when: remount_task.rc != 0
      when: not ansible_check_mode

  rescue:
    - name: Recover from failure to remount by rebooting failed hosts
      ansible.builtin.reboot:
      register: rebooted
      tags:
        - install
        - override
        - security
        - package
        - never
      when: not ansible_check_mode
