---
- hosts: "{{ host_list | default('all') }}"
  name: Playbook to configure PiKVM Hosts
  gather_facts: false

  tasks:
    - name: Include the role to complete PiKVM configuration
      ansible.builtin.include_role:
        name: pikvm
      tags:
        - install
        - override
        - baseline
        - security
        - packages

- hosts: localhost
  name: Print options for the user
  gather_facts: false

  tasks:
    - name: Make sure the user knows tags control what runs
      ansible.builtin.debug:
        msg: "Run with '--tags {{ ansible_run_tags }}'. Use 'ansible-playbook --list-tags main.yml' for options."
