---
- hosts: "{{ host_list | default('all') }}"
  name: Playbook to configure PiKVM Hosts
  tasks:
    - name: Combine group and host-specific package lists
      ansible.builtin.set_fact:
        package_list: "{{ (group_packages | default([]) + host_packages | default([])) | unique }}"

    - name: Include the role to complete PiKVM configuration
      ansible.builtin.include_role:
        name: ansible_pikvm
