# Definitely a work in progress. Quick and dirty playbook for PiKVM setup.
---
- name: Configure PiKVM
  hosts: "{{ hosts | default('all') }}"
  gather_facts: false

  pre_tasks:
    - name: Remount read-write to prepare for changes
      ansible.builtin.command: rw
      register: read_write
      changed_when: false

    - name: Combine group-specific packages with host-specific packages
      ansible.builtin.set_fact:
        package_list: "{{ (group_packages | default([]) + host_packages | default([])) | unique }}"

  tasks:
    - name: Attempt to configure PiKVM but always set SD card back to read-only
      block:
        - name: Ensure the hostname is set according to preference
          ansible.builtin.hostname:
            name: "{{ hostname | default(inventory_hostname) }}"
          register: reboot_required

        - name: Ensure the timezone is set according to preference
          community.general.timezone:
            name: "{{ timezone }}"

        - name: Ensure the mirrorlist is set according to preference
          ansible.builtin.copy:
            src: mirrorlist
            dest: /etc/pacman.d/mirrorlist
            mode: u=rw,g=r

        - name: Ensure the default root password is replaced
          ansible.builtin.user:
            name: root
            password: "{{ lookup('ansible.builtin.password', password_root, chars=['ascii_letters', 'digits', 'punctuation'], encrypt='sha512_crypt') }}"

        - name: Ensure the default kvmd admin password is replaced
          ansible.builtin.lineinfile:
            path: /etc/kvmd/htpasswd
            regexp: "^admin:"
            line: admin:{{ lookup('ansible.builtin.password', password_admin, chars=['ascii_letters', 'digits', 'punctuation'], encrypt='bcrypt') }}
          notify:
            - Reboot PiKVM

        - name: Ensure kvmd is allowed to restart or reboot itself
          ansible.builtin.copy:
            content: "kvmd ALL=(root) NOPASSWD: /usr/bin/reboot, /usr/bin/poweroff, /usr/bin/systemctl restart kvmd"
            dest: /etc/sudoers.d/ansible-kvmd
            mode: u=rw,g=r

        - name: Install preferred override.yaml set in inventory from files/
          ansible.builtin.copy:
            src: "{{ override_file }}"
            dest: /etc/kvmd/override.yaml
            mode: u=rw,g=r
          notify:
            - Restart kvmd

        - name: Install the CyberPower MIB for CyberPower ATS and PDU support
          ansible.builtin.copy:
            src: CyberPower_MIB_v2.11.MIB
            dest: /usr/share/snmp/mibs/
            mode: u=rw,g=r

        - name: Refresh the package cache and install available updates
          community.general.pacman:
            upgrade: true
            update_cache: true
          register: reboot_required
          notify:
            - Reboot PiKVM

        - name: Install additional packages from a list of desired packages
          community.general.pacman:
            name: "{{ item }}"
            state: latest
          with_items: "{{ package_list | default([]) }}"
          register: packages

        - name: Ensure the firewall rules are set as defined in the host vars
          ansible.builtin.template:
            src: public.xml.j2
            dest: /etc/firewalld/zones/public.xml
            mode: u+rw,g=r,o=r
          when: firewall_config is defined
          register: firewall_rule

        - name: Ensure the firewall service is enabled and started
          ansible.builtin.systemd:
            name: firewalld
            state: started
            enabled: true
          register: firewall_service

        # This should only run if the firewall config is changed
        - name: Reload the firewall configuration
          ansible.builtin.shell: firewall-cmd --reload
          when:
            - firewall_rule is changed and firewalld is not changed
          changed_when: true

        - name: Remount read-only to protect the SD card
          ansible.builtin.command: ro
          register: remount_task
          changed_when: remount_task.rc != 0
          failed_when: remount_task.rc != 0

      rescue:
        - name: Recover failed tasks by sending PiKVM for a reboot
          ansible.builtin.reboot:
          register: rebooted

  handlers:
    - name: Reboot PiKVM
      ansible.builtin.reboot:
      register: rebooted

    - name: Restart kvmd
      ansible.builtin.systemd:
        name: kvmd
        state: restarted
      when: rebooted is undefined
