# Definitely a work in progress. Quick and dirty playbook for PiKVM setup.
---
- name: Configure PiKVM
  hosts: all
  gather_facts: no
  tasks:
  - name: Remount root read-write to prepare the SD card for changes
    ansible.builtin.command: rw

  - name: Set PiKVM for the host (or host group's) specified timezone
    ansible.builtin.command: timedatectl set-timezone "{{ timezone }}"

  - name: Deploy the site-preferred mirrorlist from files/
    ansible.builtin.copy:
      src: mirrorlist
      dest: /etc/pacman.d/mirrorlist

  - name: Refresh the package cache and install available updates
    community.general.pacman:
      upgrade: true
      update_cache: true

  - name: Install additional packages from a list of desired packages
    community.general.pacman:
      name: "{{ item }}"
      state: latest
    with_items: "{{ package_list | default([]) }}"

  - name: Generate or set root password from files/password-root
    ansible.builtin.user:
      name: root
      password: "{{ lookup('ansible.builtin.password', password_root, chars=['ascii_letters', 'digits', 'punctuation'], encrypt='sha512_crypt') }}"

  - name: Generate or set kvmd admin password from files/password-admin
    ansible.builtin.lineinfile:
      path: /etc/kvmd/htpasswd
      regexp: '^admin:'
      line: "admin:{{ lookup('ansible.builtin.password', password_admin, chars=['ascii_letters', 'digits', 'punctuation'], encrypt='bcrypt') }}"

  - name: Install preferred override.yaml set in inventory from files/
    ansible.builtin.copy:
      src: "{{ override_file }}"
      dest: /etc/kvmd/override.yaml

  - name: Install the CyberPower MIB for CyberPower ATS and PDU support
    ansible.builtin.copy:
      src: CyberPower_MIB_v2.11.MIB
      dest: /usr/share/snmp/mibs/

  - name: Remount root read-only to protect the SD card
    ansible.builtin.command: ro
