---
# Overrides specific to pikvm1
hostname: pikvm1.openhappens.org
host_packages:
  - firewalld
  - rpi4-eeprom
  - net-snmp
# Future: Extend this for other users, using these variables for notes.
cert_paths:
  - /etc/kvmd/nginx/ssl/server.crt
  - /etc/kvmd/vnc/ssl/server.crt
msd_files:
  - https://fw-download-alias1.raspberrypi.com/net_install/boot.img

overrides:
  kvm_switch:
    # The name is optional
    name: TESmart KVM Switch
    type: tesmart
    host: 10.0.2.12
    port: 5000
    # This must be defined and match your switch
    port_range: 16
    # The button and server labels are optional
    button_text: Eat Me
    server_text: Boxen
