---
# Overrides specific to pikvm1
hostname: pikvm1.openhappens.org
ansible_host: 10.0.2.14

package_list:
  - firewalld
  - yamllint
  - rpi4-eeprom
  - net-snmp

kvmd_commands:
  - /usr/bin/reboot
  - /usr/bin/poweroff
  - /usr/bin/systemctl restart kvmd

# Presently unused, plan to use the API to add files, if possible
msd_files:
  - https://fw-download-alias1.raspberrypi.com/net_install/boot.img

# Presently unused, here to remind me to add certificate management
cert_paths:
  - /etc/kvmd/nginx/ssl/server.crt
  - /etc/kvmd/vnc/ssl/server.crt

overrides:
  gpio:
    switches:
      - name: Lab Rack 16-port TESmart Switch
        type: tesmart
        host: 10.0.2.12
        port: 5000
        size: 16

    # The button and server labels are optional
    # button_text: Eat Me
    # server_text: Boxen
    #
    #
