---
# Overrides specific to pikvm1
hostname: pikvm1.openhappens.org
ansible_host: 10.0.2.14

package_list:
  - firewalld
  - yamllint
  - rpi4-eeprom
  - net-snmp

kvmd_commands:
  - /usr/bin/reboot
  - /usr/bin/poweroff
  - /usr/bin/systemctl restart kvmd

# Presently unused, plan to use the API to add files, if possible
msd_files:
  - https://fw-download-alias1.raspberrypi.com/net_install/boot.img

# Presently unused, here to remind me to add certificate management
cert_paths:
  - /etc/kvmd/nginx/ssl/server.crt
  - /etc/kvmd/vnc/ssl/server.crt

overrides:
  gpio:
    switches:
      - name: Lab Rack 16-port TESmart Switch
        type: tesmart
        host: 10.0.2.12
        port: 5000
        size: 16
        machines: # The ":" can be problematic if unquoted here
          - { name: NUC8i7HVK, wol: ["54:b2:03:04:81:bb", "54:b2:03:04:81:bc"] }
          - { name: NUC8i7HVK, wol: ["54:b2:03:18:b1:48", "54:b2:03:18:b1:49"] }
          - { name: NUC8i7HVK, wol: ["54:b2:03:8d:4c:e9", "54:b2:03:8d:4c:ea"] }
          - { name: NUC8i7HVK, wol: ["54:b2:03:89:5b:87", "54:b2:03:89:5b:88"] }
          - { name: NUC8i7HVK, wol: ["54:b2:03:8c:ea:f4", "54:b2:03:8c:ea:f5"] }
          - { name: NUC8i7HVK, wol: ["54:b2:03:18:ac:be", "54:b2:03:18:ac:bf"] }
          - { name: NUC10i7FNH, wol: ["1c:69:7a:69:07:71"] }
          - { name: NUC10i7FNH, wol: ["1c:69:7a:0e:5d:89"] }
          - name: NUC10i7FNH
            wol:
              - 1c:69:7a:0e:5d:85 # Untested, may be a good alternative to quotes.
          - {} # Indicates empty. List placeholder if a later one is populated.
          - {} # Indicates empty. List placeholder if a later one is populated.
          - {} # Indicates empty. List placeholder if a later one is populated.
          - {} # Indicates empty. List placeholder if a later one is populated.
          - {} # Indicates empty. List placeholder if a later one is populated.
          - {} # Indicates empty. List placeholder if a later one is populated.
          - name: Laptop
