---
# Overrides specific to pikvm1
hostname: pikvm1.openhappens.org
ansible_host: 10.0.2.14

package_list:
  - firewalld
  - yamllint
  - rpi4-eeprom
  - net-snmp

# Presently unused, plan to use the API to add files, if possible
msd_files:
  - https://fw-download-alias1.raspberrypi.com/net_install/boot.img

# Presently unused, here to remind me to add certificate management
cert_paths:
  - /etc/kvmd/nginx/ssl/server.crt
  - /etc/kvmd/vnc/ssl/server.crt

# Debating this structure. For PiKVM it makes sense to have sections, but for
# the playbook purpose it doesn't matter that "switches" go under "kvmd.gpio",
# that logic is in the template for the final rendered override.yaml.
overrides:
  gpio:
    title: KVM Switch
    commands:
      - name: Restart kvmd
        command: [/usr/bin/sudo, /usr/bin/systemctl, restart, kvmd]
        confirm: true
      - name: Reboot
        command: [/usr/bin/sudo, /usr/bin/reboot]
        confirm: true
      - name: Test
        command: [/usr/bin/test, test2, ==, test3]
    switches:
      - hostname: Lab Rack 16-port TESmart Switch
        type: tesmart
        host: 10.0.2.12
        port: 5000
        size: 16
        machines:
          - hostname: NUC8i7HVK
            macaddrs:
              - 54:b2:03:04:81:bb
              - 54:b2:03:04:81:bc
          - hostname: NUC8i7HVK
            macaddrs:
              - 54:b2:03:18:b1:48
              - 54:b2:03:18:b1:49
          - hostname: NUC8i7HVK
            macaddrs:
              - 54:b2:03:8d:4c:e9
              - 54:b2:03:8d:4c:ea
          - hostname: NUC8i7HVK
            macaddrs:
              - 54:b2:03:89:5b:87
              - 54:b2:03:89:5b:88
          - hostname: NUC8i7HVK
            macaddrs:
              - 54:b2:03:8c:ea:f4
              - 54:b2:03:8c:ea:f5
          - hostname: NUC8i7HVK
            macaddrs:
              - 54:b2:03:18:ac:be
              - 54:b2:03:18:ac:bf
          - hostname: NUC10i7FNH
            macaddrs:
              - 1c:69:7a:69:07:71
          - hostname: NUC10i7FNH
            macaddrs:
              - 1c:69:7a:0e:5d:89
          - hostname: NUC10i7FNH
            macaddrs:
              - 1c:69:7a:0e:5d:85
          - {} # Indicates empty. List placeholder if a later one is populated.
          - {} # Indicates empty. List placeholder if a later one is populated.
          - {} # Indicates empty. List placeholder if a later one is populated.
          - {} # Indicates empty. List placeholder if a later one is populated.
          - {} # Indicates empty. List placeholder if a later one is populated.
          - {} # Indicates empty. List placeholder if a later one is populated.
          - hostname: Laptop
