---
# handlers file for ansible_pikvm
- name: Reboot PiKVM
  ansible.builtin.reboot:
  register: rebooted

- name: Restart kvmd
  ansible.builtin.systemd:
    name: kvmd
    state: restarted
  when: rebooted is undefined
