---
# handlers file for pikvm
- name: Reboot PiKVM
  ansible.builtin.reboot:
  register: rebooted
  when: rebooted is undefined

- name: Restart kvmd
  ansible.builtin.systemd:
    name: kvmd
    state: restarted
  when: rebooted is undefined
